"""initial LAGGENTE schema

Revision ID: 5258d1a3248a
Revises:
Create Date: 2026-08-22 16:28:22.428889
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5258d1a3248a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=True),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_event_account_created', 'events', ['account_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_events_account_id'), 'events', ['account_id'], unique=False)
    op.create_index(op.f('ix_events_conversation_id'), 'events', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_events_space_id'), 'events', ['space_id'], unique=False)
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_members_account_id'), 'members', ['account_id'], unique=False)
    op.create_index(op.f('ix_members_email'), 'members', ['email'], unique=True)
    op.create_table('spaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('professional_name', sa.String(length=200), nullable=False),
    sa.Column('agency', sa.String(length=200), nullable=True),
    sa.Column('territory', sa.String(length=300), nullable=True),
    sa.Column('public_role', sa.String(length=100), nullable=False),
    sa.Column('locale', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_revision_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_space_slug')
    )
    op.create_index(op.f('ix_spaces_account_id'), 'spaces', ['account_id'], unique=False)
    op.create_index(op.f('ix_spaces_active_revision_id'), 'spaces', ['active_revision_id'], unique=False)
    op.create_index(op.f('ix_spaces_slug'), 'spaces', ['slug'], unique=False)
    op.create_table('config_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('proposed_by_member_id', sa.String(length=36), nullable=True),
    sa.Column('activated_by_member_id', sa.String(length=36), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('space_id', 'revision_number', name='uq_space_revision_number')
    )
    op.create_index('ix_config_revision_account_space', 'config_revisions', ['account_id', 'space_id'], unique=False)
    op.create_index(op.f('ix_config_revisions_account_id'), 'config_revisions', ['account_id'], unique=False)
    op.create_index(op.f('ix_config_revisions_space_id'), 'config_revisions', ['space_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=True),
    sa.Column('visitor_token_hash', sa.String(length=64), nullable=True),
    sa.Column('automatic_ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('professional_joined', sa.Boolean(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_account_kind', 'conversations', ['account_id', 'kind'], unique=False)
    op.create_index('ix_conversation_account_space', 'conversations', ['account_id', 'space_id'], unique=False)
    op.create_index(op.f('ix_conversations_account_id'), 'conversations', ['account_id'], unique=False)
    op.create_index(op.f('ix_conversations_space_id'), 'conversations', ['space_id'], unique=False)
    op.create_index(op.f('ix_conversations_visitor_token_hash'), 'conversations', ['visitor_token_hash'], unique=True)
    op.create_table('magic_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_account_id'), 'magic_links', ['account_id'], unique=False)
    op.create_index(op.f('ix_magic_links_member_id'), 'magic_links', ['member_id'], unique=False)
    op.create_index(op.f('ix_magic_links_token_hash'), 'magic_links', ['token_hash'], unique=True)
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_type', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index('ix_attachment_account_conversation', 'attachments', ['account_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_attachments_account_id'), 'attachments', ['account_id'], unique=False)
    op.create_index(op.f('ix_attachments_conversation_id'), 'attachments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_attachments_message_id'), 'attachments', ['message_id'], unique=False)
    op.create_index(op.f('ix_attachments_space_id'), 'attachments', ['space_id'], unique=False)
    op.create_table('memory_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('space_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('corrected_content', sa.Text(), nullable=True),
    sa.Column('corrected_by_member_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memory_account_conversation', 'memory_items', ['account_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_items_account_id'), 'memory_items', ['account_id'], unique=False)
    op.create_index(op.f('ix_memory_items_conversation_id'), 'memory_items', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_items_space_id'), 'memory_items', ['space_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('author_type', sa.String(length=32), nullable=False),
    sa.Column('author_label', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=40), nullable=False),
    sa.Column('client_message_id', sa.String(length=100), nullable=True),
    sa.Column('model_response_id', sa.String(length=100), nullable=True),
    sa.Column('assistant_reply_state', sa.String(length=24), nullable=True),
    sa.Column('reply_to_message_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'client_message_id', name='uq_conversation_client_message'),
    sa.UniqueConstraint('reply_to_message_id', name='uq_message_reply_to')
    )
    op.create_index('ix_message_account_conversation', 'messages', ['account_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_account_id'), 'messages', ['account_id'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_account_id'), table_name='messages')
    op.drop_index('ix_message_account_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_memory_items_space_id'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_conversation_id'), table_name='memory_items')
    op.drop_index(op.f('ix_memory_items_account_id'), table_name='memory_items')
    op.drop_index('ix_memory_account_conversation', table_name='memory_items')
    op.drop_table('memory_items')
    op.drop_index(op.f('ix_attachments_space_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_message_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_conversation_id'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_account_id'), table_name='attachments')
    op.drop_index('ix_attachment_account_conversation', table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_magic_links_token_hash'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_member_id'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_account_id'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_conversations_visitor_token_hash'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_space_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_account_id'), table_name='conversations')
    op.drop_index('ix_conversation_account_space', table_name='conversations')
    op.drop_index('ix_conversation_account_kind', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_config_revisions_space_id'), table_name='config_revisions')
    op.drop_index(op.f('ix_config_revisions_account_id'), table_name='config_revisions')
    op.drop_index('ix_config_revision_account_space', table_name='config_revisions')
    op.drop_table('config_revisions')
    op.drop_index(op.f('ix_spaces_slug'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_active_revision_id'), table_name='spaces')
    op.drop_index(op.f('ix_spaces_account_id'), table_name='spaces')
    op.drop_table('spaces')
    op.drop_index(op.f('ix_members_email'), table_name='members')
    op.drop_index(op.f('ix_members_account_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_events_space_id'), table_name='events')
    op.drop_index(op.f('ix_events_conversation_id'), table_name='events')
    op.drop_index(op.f('ix_events_account_id'), table_name='events')
    op.drop_index('ix_event_account_created', table_name='events')
    op.drop_table('events')
    op.drop_table('accounts')
    # ### end Alembic commands ###
